### ISSUE TITLE
add tests!!!

### ISSUE THREAD

**Issue by soldair** [npm/scope-it#11]
we need tests asap!

use `tape`

**Comment by mrlannigan** [comment]
How do you suggest we test the commit of the file while using a sub process (rewrite-js)?

**Comment by soldair** [comment]
i think we'll have to create fixture packages
`cp -fr fixture/package-has-wacky-requires ./test/date.now()/`
run `rewrite-js`
and `fs.readFile` the files to make sure things are as they should be.

perhaps just run `npm test` in the fixture module itself to make sure it still functions.
