### ISSUE TITLE
scope-it does not deal with AST parse errors in a friendly manner

### ISSUE THREAD

**Issue by jangie** [npm/scope-it#4]
When scope-it is passed a file that has (e.g.) es6 features and dry-run is off, it will write json describing the parse error into the original file.

Instead of clobbering files on parse error, it would be nice if scope-it instead wrote a text file with json describing which files it was not able to deal with, and put the parse error json there as well.

**Comment by soldair** [comment]
oooh sorry this hit you. it should have never gotten there ill look.

**Comment by soldair** [comment]
have a fix. testing now

**Comment by soldair** [comment]
fixed in 1.0.5
now i wont overwrite the files contents if the command fails or crashes! =)

messaging is really bad as it doesn't print the file that had the parse error. ill need to land a pr in rewrite-js tomorrow

**Comment by jangie** [comment]
Thanks @soldair ! Is it likely that the tool will support es6 source? If not, I'm slightly worried about issue #5 being resolved because it means that mixed es5-es6 code bases will completely not be migrated.

Thanks again!

**Comment by soldair** [comment]
I'll check into it. It is uses cssauron under the hood so I imagine it's
not super difficult though it will be work.
