### ISSUE TITLE
es6 support

### ISSUE THREAD

**Issue by soldair** [npm/scope-it#6]

**Comment by soldair** [comment]
looks like we can resolve this by passing options
https://github.com/chrisdickinson/rewrite-js/issues/5

**Comment by jangie** [comment]
Once chrisdickinson/rewrite-js#6 is merged, I believe that the options we would want to pass are:
{"sourceType":"module","ecmaVersion":6}

**Comment by soldair** [comment]
Wow great!

**Comment by soldair** [comment]
we will probably have to add a selector to write `import` also

**Comment by jangie** [comment]
Yeah... I was trying the other day to figure out what magical set of keywords would match `import`, but was thoroughly flummoxed. I don't know enough about what is expected by the parser, I guess.

**Comment by soldair** [comment]
so i think we have es6 support now. i can close this an open an issue for supporting scope rewrite of import declarations
