### ISSUE TITLE
Change in rewrite-js breaks this module

### ISSUE THREAD

**Issue by mrlannigan** [npm/scope-it#7]
chrisdickinson/rewrite-js@df02d62c6c77c390a3cc1e582fd41d0e028aa7ca

Switches the argument usage from cooked to remain, which in turn causes both the scope and modules to be required in the same way the transform.js is loaded. Generally all the additional paths don't exist in the scope-it directory and so the process fails.

chrisdickinson/rewrite-js#7 seems to correct the issue that I am seeing.

Unfortenately, without reverting to the previous working version of rewrite-js or manually making the change, this module doesn't work.

**Comment by soldair** [comment]
i pinged @chrisdickinson again. hopefully we'll get this merged asap.

**Comment by jangie** [comment]
for now, while we wait on the merge, should we lock the rewrite-js version instead of using ^1.0.4 ?

**Comment by soldair** [comment]
i thinl ill publish a fork of rewrite-js to npm as @soldair/rewrite-js till this gets resolved. one sec

**Comment by soldair** [comment]
ok published 1.0.6 to npm which depends on `@soldair/rewrite-js` fork with jangie's fix
if it works we can close this for now

**Comment by mrlannigan** [comment]
Confirmed chrisdickinson/rewrite-js#7 fixed this issue and has been released to the npm registry.
